### ISSUE TITLE
Error in sd_boot.bif files for standalone for RPU on VCK190-ES1

### ISSUE THREAD

**Issue by delorytheape** [Xilinx/Embedded-Design-Tutorials#3]
The SD_BOOT.bif files that are provided for building standalone for the RPU (R5) on the VCK190-ES1 are incorrect.
ie. <base directory>/docs/Introduction/Versal-EDT/ref_files/ES1/vck190/standalone/cips_noc/rpu/sd_boot.bif 
and
<base directory>/docs/Introduction/Versal-EDT/ref_files/ES1/vck190/standalone/cips_/rpu/sd_boot.bif

Line10 should read
{core=r5-0, file=helloworld_r5.elf }

**Comment by dasmohana** [comment]
This is resolved in the 2021.2 update. You can find the updated design files here: https://github.com/Xilinx/Embedded-Design-Tutorials/tree/master/docs/Introduction/Versal-EDT/ref_files
