### ISSUE TITLE
Vitis-workspace.tcl link broken in Vitis Embedded SW Debugging guide

### ISSUE THREAD

**Issue by dhill972** [Xilinx/Embedded-Design-Tutorials#34]
The link for the vitis-workspace.tcl file (https://xilinx.github.io/Embedded-Design-Tutorials/docs/2022.2/build/html/docs/Vitis-Embedded-Software-Debugging/docs/3-debugging-linux-applications/script/Vitis-workspace.tcl) in step #6 of the Debugging Linux Applications (https://xilinx.github.io/Embedded-Design-Tutorials/docs/2022.1/build/html/docs/Vitis-Embedded-Software-Debugging/docs/3-debugging-linux-applications/README.html) page is broken or the file is missing. 

We tried the 2021.1 link (https://xilinx.github.io/Embedded-Design-Tutorials/docs/2021.1/build/html/docs/Vitis-Embedded-Software-Debugging/docs/3-debugging-linux-applications/script/Vitis-workspace.tcl) and its broken as well.

**Comment by ryanvergel** [comment]
This content has been moved to https://github.com/Xilinx/Vitis-Tutorials/tree/2023.2/Embedded_Software/Feature_Tutorials/02-Debugging
