### ISSUE TITLE
Error in documentation (incorrect boot switch setting)

### ISSUE THREAD

**Issue by delorytheape** [Xilinx/Embedded-Design-Tutorials#4]
The document page <base>/docs/Introduction/Versal-EDT/docs/4-boot-and-config.md contains an error.
The photograph of SW1 in step 4 of "Boot Sequence For SD-Boot Mode" is incorrect. (It shows switch configured for QSPI boot mode, not SD-card boot mode). It should be SW1[4,3,2,1] = off,off,off,on (ie. the same as the photo in step 2 of "Boot Sequence For QSPI Boot Mode")

**Comment by dasmohana** [comment]
This is resolved in the 2021.2 update. Please see: https://xilinx.github.io/Embedded-Design-Tutorials/docs/2021.2/build/html/docs/Introduction/Versal-EDT/docs/4-boot-and-config.html#boot-sequence-for-sd-boot-mode
